### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fmeneuhe** [mikepenz/Android-Iconics#155]
Hi,
I got this crash: 

```java
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=1 dstPos=1 length=1
       at java.lang.System.arraycopy(System.java)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:907)
       at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:826)
       at android.text.SpannableStringBuilder.sendSpanRemoved(SpannableStringBuilder.java:1058)
       at android.text.SpannableStringBuilder.clearSpans(SpannableStringBuilder.java:253)
       at com.mikepenz.iconics.utils.IconicsUtils.findIconsFromEditable(SourceFile:43)
       at com.mikepenz.iconics.Iconics.styleEditable(SourceFile:195)
       at com.mikepenz.iconics.Iconics.styleEditable(SourceFile:178)
       at com.mikepenz.iconics.context.IconicsFactory$1.afterTextChanged(SourceFile:75)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:8007)
       at android.widget.TextView.setText(TextView.java:4355)
       at android.widget.TextView.setText(TextView.java:4203)
       at android.widget.TextView.setText(TextView.java:4178)
       at com.apolosoft.table.views.CellView$24.run(SourceFile:2359)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5514)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I think its releated with Material Iconicis lib, but not 100% sure.

**Comment by mikepenz** [comment]
@fmeneuhe how did you get this crash?

**Comment by fmeneuhe** [comment]
To be honest I do not know, it crashed in ome of my users and it has been reported authomatically. I will try to ask the user.

**Comment by mikepenz** [comment]
@fmeneuhe ok thanks. In addition it is also important which version you used and which elements of the Android-Iconics you use

**Comment by fmeneuhe** [comment]
I use these versions and fonts:

    compile 'com.mikepenz:iconics-core:2.5.8@aar'

    compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
    compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
    compile 'com.mikepenz:ionicons-typeface:2.0.1.1@aar'

**Comment by mikepenz** [comment]
@fmeneuhe not sure what really happens but seems to be a platform issue. 

```java
editable.clearSpans();
```

the app crashed with the above code
