### ISSUE TITLE
App Crashed show that "java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/view/menu/ActionMenuItemView;"

### ISSUE THREAD

**Issue by JohnnyShieh** [mikepenz/Android-Iconics#164]
The error info is following:
`at com.mikepenz.iconics.context.IconicsFactory.onViewCreatedInternal(IconicsFactory.java:44)
at com.mikepenz.iconics.context.IconicsFactory.onViewCreated(IconicsFactory.java:28)
at com.mikepenz.iconics.context.IconicsLayoutInflater.onCreateView(IconicsLayoutInflater.java:24)
at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)`

I guess is that,` import android.support.v7.view.menu.ActionMenuItemView;` should be replaced to `import android.support.v7.internal.view.menu.ActionMenuItemView`

**Comment by JohnnyShieh** [comment]
I got the answer, The reason is that the package of ActionMenuItemView  is `android.support.v7.internal.view.menu.ActionMenuItemView` when appcompatVersion is **23.0.1**.

**Comment by mikepenz** [comment]
@JohnnyShieh You might even need to use the latest **v23.3.0** as the Iconics already use the latest onve
