### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by Ewg777** [mikepenz/Android-Iconics#165]
@mikepenz you've made a great lib! How to fix it?
Crashed on release configuration with proguard
Error stacktrace 
```java
 Caused by: java.lang.NullPointerException
 at java.lang.Enum$1.create(Enum.java:43)
 at java.lang.Enum$1.create(Enum.java:35)
 at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
 at java.lang.Enum.getSharedConstants(Enum.java:209)
 at java.lang.Enum.valueOf(Enum.java:189)
 at com.mikepenz.google_material_typeface_library.a.k(SourceFile:123)
 at com.mikepenz.google_material_typeface_library.GoogleMaterial.getIcon(SourceFile:37)
 at com.mikepenz.iconics.utils.IconicsUtils.placeFontIcon(SourceFile:219)
 at com.mikepenz.iconics.utils.IconicsUtils.findIcons(SourceFile:164)
 at com.mikepenz.iconics.Iconics.style(SourceFile:159)
 at com.mikepenz.iconics.Iconics$IconicsBuilderString.build(SourceFile:221)
 at com.mikepenz.iconics.view.IconicsTextView.setText(SourceFile:42)
 at android.widget.TextView.setText(TextView.java:3683)
```
my_activity.xml:
```xml

        <com.mikepenz.iconics.view.IconicsTextView
            android:id="@+id/asd"
            android:textColor="@color/colorPrimary"
            android:textSize="28sp" />
```

MyActivity.java
```java

public class MyActivity extends AppCompatActivity {
    @Bind(R.id.asd)
    protected IconicsTextView asd;
    @Override
    public void onCreate(Bundle savedInstanceState) {
        setContentView(R.layout.my_activity);
...
        asd.setText("{gmd-cloud-off}");
    }
```

**Comment by mikepenz** [comment]
@Ewg777 your proguard rule destroys the enum used inside the `GoogleMaterial` font. 
You will need to keep the enum as described here:
http://stackoverflow.com/a/6286534/325479

Seems like your proguard configuration is very strict

**Comment by Ewg777** [comment]
@mikepenz thanks! 
This is solved the issue:
```java
-keep public enum com.mikepenz.google_material_typeface_library.GoogleMaterial$** {
    **[] $VALUES;
    public *;
}
```
