### ISSUE TITLE
android.graphics.Typeface.getStyle() on a null object reference error

### ISSUE THREAD

**Issue by murtaza61** [mikepenz/Android-Iconics#185]
stack trace is

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Typeface.getStyle()' on a null object reference
                                                                                at com.mikepenz.iconics.utils.IconicsTypefaceSpan.applyCustomTypeFace(IconicsTypefaceSpan.java:51)
                                                                                at com.mikepenz.iconics.utils.IconicsTypefaceSpan.updateDrawState(IconicsTypefaceSpan.java:34)
                                                                                at android.text.TextLine.handleRun(TextLine.java:932)
                                                                                at android.text.TextLine.measureRun(TextLine.java:417)
                                                                                at android.text.TextLine.measure(TextLine.java:296)
                                                                                at android.text.TextLine.metrics(TextLine.java:270)
                                                                                at android.text.BoringLayout.isBoring(BoringLayout.java:311)
                                                                                at android.widget.TextView.onMeasure(TextView.java:6880)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1283)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:391)
                                                                                at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:419)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1560)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:391)
                                                                                at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:419)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                at android.view.View.measure(View.java:18805)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                at android.view.View.measure(View.java:18805)
                                                                            	at android.view.ViewRootImpl.perf
```
if i uninstall my apk on phone and reinstall there is no error

**Comment by mikepenz** [comment]
could you please provide a sample app or code which allows me to reproduce this issue?

**Comment by murtaza61** [comment]
i think this is ide bug. Now there is no error.

**Comment by mikepenz** [comment]
Ok great :)
