### ISSUE TITLE
Issue while previewing the layout xml in Android Studio

### ISSUE THREAD

**Issue by raviteja06** [mikepenz/Android-Iconics#210]
Tho, I am able to see the icon in the actual application, the Android Studio preview shows below exception

**Using latest 2.7.2** 

```
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Float.needRoom(Path2D.java:323)
	at java.awt.geom.Path2D.closePath(Path2D.java:1876)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:816)
	at android.graphics.Path_Delegate.native_close(Path_Delegate.java:323)
	at android.graphics.Path.native_close(Path.java)
	at android.graphics.Path.close(Path.java:480)
	at com.mikepenz.iconics.IconicsDrawable.onBoundsChange(IconicsDrawable.java:839)
	at android.graphics.drawable.Drawable.setBounds(Drawable.java:168)
	at android.widget.ImageView.configureBounds(ImageView.java:1111)
	at android.widget.ImageView.setFrame(ImageView.java:1089)
	at android.view.View.layout(View.java:16626)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:376)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:428)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:520)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:508)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:508)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:75)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:620)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:617)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:371)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:617)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:639)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:654)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:596)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:591)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

PS: This issue is similar to #107

**Comment by mikepenz** [comment]
@raviteja06 is this exception new?

**Comment by raviteja06** [comment]
@mikepenz Yes, its new.

In issue #107 its throwing execption at com.mikepenz.iconics.IconicsDrawable.draw(IconicsDrawable.java:749) but in current one the execption throwing at  com.mikepenz.iconics.IconicsDrawable.onBoundsChange(IconicsDrawable.java:839).

I rollbacked to 2.5.11 and its not showing any execption. 

Thanks in advance.

**Comment by mikepenz** [comment]
@raviteja06 how do you define the `IconicsDrawable` to be drawn in your layout?

**Comment by raviteja06** [comment]
@mikepenz 
In java
`new IconicsDrawable(context).icon(icon)`

In XML
 <com.mikepenz.iconics.view.IconicsImageView
                android:id="@+id/verified"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:alpha="0.7"
                android:background="@color/green_button_text"
                app:iiv_color="@color/white"
                app:iiv_icon="svo-verify" />

I am using our own file imported from font folder and icons defined in application class using GenericFont class

Let me know if you need any information.

**Comment by mikepenz** [comment]
@raviteja06 so it also throws an exception when you use it programatically not only via xml?

**Comment by raviteja06** [comment]
Only in XML. It shows the exception in the preview window. No issue while running app.

**Comment by mikepenz** [comment]
@raviteja06 can't reproduce this. everything works fine as intended when I open the preview window with the sample layouts in the latest Android Studio. (it won't show the icon, but also no exception. which is the correct behavior)

**Comment by raviteja06** [comment]
@mikepenz Thanks for the effort. I'll try again and will see if I can solve it from my side.
