### ISSUE TITLE
IndexOutOfBoundsException in ListView

### ISSUE THREAD

**Issue by nfranke** [mikepenz/Android-Iconics#216]
If I use a TextView containing an iconics icon set via setText using the { } notation, I see consistent crashes when scrolling. If I replace the TextView with a com.mikepenz.iconics.view.IconicsTextView there is no crash.

```
08-19 14:33:56.970 1507-1507/com.myasd.asdmobile E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myasd.asdmobile, PID: 1507
        java.lang.IndexOutOfBoundsException: charAt: 3 >= length 1
        at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:119)
        at android.text.Layout.getLineVisibleEnd(Layout.java:1227)
        at android.text.Layout.drawText(Layout.java:287)
        at android.widget.Editor.drawHardwareAccelerated(Editor.java:1585)
        at android.widget.Editor.onDraw(Editor.java:1507)
        at android.widget.TextView.onDraw(TextView.java:5715)
        at android.view.View.draw(View.java:16178)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.View.draw(View.java:15948)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15169)
        at android.view.View.draw(View.java:15948)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.widget.ListView.drawChild(ListView.java:3416)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:2591)
        at android.widget.ListView.dispatchDraw(ListView.java:3411)
        at android.view.View.draw(View.java:16181)
        at android.widget.AbsListView.draw(AbsListView.java:4142)
        at android.view.View.updateDisplayListIfDirty(View.java:15174)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15134)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java
```

If it helps, my layout entry is:

>     <com.mikepenz.iconics.view.IconicsTextView
>         android:id="@+id/cell_icon"
>         android:layout_width="@dimen/icon_cell_width"
>         android:layout_height="wrap_content"
>         android:textColor="@android:color/black"
>         android:layout_gravity="center_vertical"
>         android:text="X"
>         android:textSize="24dp" />
>

**Comment by mikepenz** [comment]
@nfranke hmm weird. Especially as the above does not have any reference to the `Iconics` library. It may be resulted through the spans being handled a bit differently. 

Would you be able to just use the `IconicsTextView` in your case? As it just extends from `TextView` anyway.

**Comment by nfranke** [comment]
Sorry, I wasn't able to respond this weekend. I did switch to the IconicsTextView class and that works fine.

**Comment by pdalfarr** [comment]
Very same crash here when I set text with some {whatever_icon_codes} in a TextView.
Using an IconicsTextView solves the problem.

This should be documented, right?

thanks a lot for this great library ;-)

**Comment by mikepenz** [comment]
@pdalfarr I am happy to take a PR to add it somewhere in a FAQ or so :D 

I'd prefer though to figure out the real reason for this. because the TextView should not behave like this :D

**Comment by pdalfarr** [comment]
@mikepenz  FYI, the 'invalid char is probably ⌧ ( http://www.fileformat.info/info/unicode/char/2327/index.htm )

Basically, I am adding lines in an IconicsTextView , each of them starting with either {gmd_cloud_queue} or {gmd_favorite_border}
And only the first {gmd_cloud_queue} or {gmd_favorite_border} is replaced by an icon, all the other that follow (may they be  {gmd_cloud_queue} or {gmd_favorite_border}) ar replaced by something similar to ⌧ (not exactly that: not horizontally stretched, but vertically stretched)

Any idea? did you try to add many lines in a IconicsTextView, each of them starting with an icon : "{icon_code_1} ... line1\n{icon_code_2} ... line2" etc...

(OMG, how can I force these images to be displayed smaller)?


![image](https://user-images.githubusercontent.com/1537201/43584775-a7c49448-9663-11e8-99f6-fd5ec44b6f6e.png)

![image](https://user-images.githubusercontent.com/1537201/43584819-c5799b1e-9663-11e8-854a-450e2f524e7d.png)

**Comment by mikepenz** [comment]
⌧ means normally that the unicode character is not found. 

Basically the way how the library is work it uses the normal text rendering. So it's fast and efficient. 

So to set an icon at a position it searches for the occurrence of a placeholder and will replace that one with the representing character and applies a TypeFaceSpannable on it (to set the font for it). 

It seems that the normal textView somehow has a race condition where it does not realize that the text was changed and has now a different length or so..

**Comment by pdalfarr** [comment]
My mistake...

I am using getText , changing the text programmatically,  then using setText... that's why the next lines have these 'not found 'characters.
So, that's quite normal since your library changed the {whatever} to a spannable and I am 'breaking' this because of my string manipulation.
I changed my code and now it's working fine.

Thanks for your time ;-)
