### ISSUE TITLE
[Issue] with changing IconicButton to have an icon in class

### ISSUE THREAD

**Issue by DasserBasyouni** [mikepenz/Android-Iconics#266]
I was trying to get a button to have an icon at certain condition so, I test this line at onCreate first
`button.setText("{faw-repeat} " + button.getText());`
It have made the button works with icon very well but after nearly 5 seconds it FC cuz of this Logcat
also I have changed the button color to red while it was having the app color (pinky) with the style
`style="?android:attr/buttonBarButtonStyle"`

```
project.com....s E/AndroidRuntime: FATAL EXCEPTION: main
Process: project.com.....s, PID: 11077
java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassCastException: com.mikepenz.iconics.context.IconicsContextWrapper cannot be cast to android.app.ContextImpl
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2735)
at android.app.ActivityThread.access$2100(ActivityThread.java:159)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5570)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.ClassCastException: com.mikepenz.iconics.context.IconicsContextWrapper cannot be cast to android.app.ContextImpl
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2715)
at android.app.ActivityThread.access$2100(ActivityThread.java:159) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:
at android.app.ActivityThread.main(ActivityThread.java:
at java.lang.reflect.Method.invoke(Native 
at java.lang.reflect.Method.invoke(Method.java:
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
```

**Comment by mikepenz** [comment]
@DasserBasyouni the crash isn't directly happening from the library. it happens because of firebase. 

As this is not working (as of firebase's fault) simply use the `IconicsDrawable` as compound drawable

**Comment by DasserBasyouni** [comment]
thank you `setCompoundDrawables` solves the FC
