### ISSUE TITLE
Android App crashes

### ISSUE THREAD

**Issue by henningvs** [mikepenz/Android-Iconics#285]
After todays update the Android App (Iconics Library) directly crashes with this error:
```
05-26 14:57:49.133 17428-17428/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mikepenz.iconics.sample, PID: 17428
                                                   java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;)V in class Lcom/mikepenz/materialize/holder/StringHolder; or its super classes (declaration of 'com.mikepenz.materialize.holder.StringHolder' appears in /data/app/com.mikepenz.iconics.sample-1/base.apk)
                                                       at com.mikepenz.materialdrawer.holder.StringHolder.<init>(StringHolder.java:10)
                                                       at com.mikepenz.materialdrawer.model.BaseDrawerItem.withName(BaseDrawerItem.java:95)
                                                       at com.mikepenz.iconics.sample.MainActivity.onCreate(MainActivity.java:90)
                                                       at android.app.Activity.performCreate(Activity.java:6760)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mikepenz** [comment]
@henningvs you are using the `MaterialDrawer`?

**Comment by mychaelgo** [comment]
hi @mikepenz , i downloaded android iconics on google play store, but when i open it, it crashed.

**Comment by mikepenz** [comment]
@mychaelgo oh really? Do you have a crash log for me or something?

**Comment by mikepenz** [comment]
or is it the same crash as above?

**Comment by henningvs** [comment]
@mikepenz sorry for the confusion. This was exactly what I wanted to report. 
Not a bug with my own app but rather a bug with your app. The stacktrace origins from this app, which should be yours (hopefully): https://play.google.com/store/apps/details?id=com.mikepenz.iconics.sample

I did not find a better channel to report it.

**Comment by mikepenz** [comment]
@henningvs oh ok sorry I didn't get that point. The problem is this crash does not happen on any of my devices :/ 

Well I have the debug variant installed. I have to see. Thanks for reporting it

**Comment by henningvs** [comment]
If I coule help you in any way to reproduce the bu let me know. I guess it's not open source so I can't build a debug version for my device? 
I use a Oneplus 3T with Android 7.1.1 by the way. And the problem did not occur with the previous app version.

**Comment by mikepenz** [comment]
I installed the release edition and got the crash. Fixing it right now :). 

And it is open source by the way (just see the "app" folder in this repo)

**Comment by mikepenz** [comment]
Fixed it and pushed a new release to the playstore

**Comment by mychaelgo** [comment]
@mikepenz nice, thank you for fast response 👍
