### ISSUE TITLE
shrinkResources removes abc_hint_foreground_material_light.xml

### ISSUE THREAD

**Issue by jazzgil** [mikepenz/Android-Iconics#289]
Hi,

My app runs fine in debug mode, but in release (specifically when shrinkResources is true), I get an exception immediately when the app loads, with:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class TextView
Caused by: android.content.res.Resources$NotFoundException: File res/color/abc_hint_foreground_material_light.xml from color state list resource ID #0x7f060006
at android.content.res.Resources.loadColorStateListForCookie(Resources.java:4336)
at android.content.res.Resources.loadColorStateList(Resources.java:4285)
at android.content.res.TypedArray.getColorStateList(TypedArray.java:487)
at android.widget.TextView.<init>(TextView.java:1026)
at android.widget.TextView.<init>(TextView.java:941)
at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029
```

I'm using:
    compile "com.mikepenz:iconics-core:2.8.5@aar"
    compile 'com.mikepenz:google-material-typeface:3.0.1.0.original@aar'

I've found that this file is part of google_material_typeface_library. 
Any idea why it looks for this file, or if it is necessary, why shrinkResources truncates it?

EDIT:
Perhaps this is a bug gradle bug in AS 3.0 canary 2.

Thanks,
Gilad

**Comment by mikepenz** [comment]
@jazzgil well why do you use this color? `abc_hint_foreground_material_light` it's provided by the support libraries I guess, and there is a high chance of it getting removed. 
In addition this does not really seem to be a `Android-Iconics` issue. Just define your own color, and you are fine.

**Comment by jazzgil** [comment]
I'm not, as far as I know. I thought google_material_typeface_library might be the culprit, as I found references to it there.
I'm using the theme Theme.AppCompat.Light.DarkActionBar. Do you think it might be related?

Thanks!

**Comment by mikepenz** [comment]
@jazzgil well the resource you use comes from some support library. Please just define your own color and you should be fine

**Comment by jazzgil** [comment]
Solved with AS3 canary 4.

**Comment by rakeshdhreport** [comment]
@jazzgil  Can you please tell, how did you solved?
