### ISSUE TITLE
Index out of bounds exception when using setText() in fragment

### ISSUE THREAD

**Issue by DrFornax** [mikepenz/Android-Iconics#350]
I'm new to the project and try to display some text in my app, which contains icons.

A server sends messages and can then add something like {gmd_play_arrow} to the text.

However, when I try to change the text of a button, I always get an index out of bound exception.

```
private Button myButton;
 myButton = (Button) act.findViewById(R.id.buttonPlayRecord);
myButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
             
                switch (Server().getRecorderMode()) {
                    case PLAY_MODE: {
                        mSimButtonMode.setText("{cmd_record}");
                    }
                    case RECORD_MODE: {
                        mSimButtonMode.setText("{cmd_play}");
                    }
                }

            }
        });
```

I added the following to my activity:

```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
```

I have had the hope that there is some link to a place wehre I can ask questions first (slack, irc, StackOverflow) but only found the issues section. Probably there is another way to ask first before I raise a ticket?

Thank you very much.

**Comment by zTrap** [comment]
@DrFornax I’ll check your issue tomorrow (now I have no time). You can use `IconicsCheckBox` or `IconicsCompoundButton` from our views-module as another option.

**Comment by mikepenz** [comment]
@DrFornax if you have an icon only. consider using an `IconicsImageView` or `IconicsButton`

**Comment by mikepenz** [comment]
@DrFornax could you please post the exact out of bounds exception? 

Just tried it in the sample application and I am not able to reproduce

**Comment by DrFornax** [comment]
I'm very sorry that it took a week to answer but I was one week out of the project.

I tried to dive a little deeper into the problem, but the stack trace does not give me an idea where to look for the problem. It occurs whenever I want to update a text of a UI Element such as a label with setText and when I add an icon tag inside the text such as ""{cmd_database} Loading from database"

Unfortunately it is no icon only but a text mixed with icons.

Here is the stack trace. Thank you for your help and let me hear if you need more information:

```
11-09 22:12:54.669 11723-11723/de.app W/System.err: java.lang.IndexOutOfBoundsException
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.graphics.Canvas.drawTextRun(Canvas.java:1813)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.TextLine.drawTextRun(TextLine.java:963)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.TextLine.handleText(TextLine.java:760)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.TextLine.handleRun(TextLine.java:932)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.TextLine.drawRun(TextLine.java:368)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.TextLine.draw(TextLine.java:196)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.text.Layout.drawText(Layout.java:399)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.widget.Editor.drawHardwareAccelerated(Editor.java:1908)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.widget.Editor.onDraw(Editor.java:1830)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.widget.TextView.onDraw(TextView.java:5865)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17237)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16219)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16182)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17240)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16219)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16214)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17240)
11-09 22:12:54.669 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16219)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16214)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16214)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17003)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.draw(View.java:17240)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at com.android.internal.policy.DecorView.draw(DecorView.java:757)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16219)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:621)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.os.Looper.loop(Looper.java:241)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6274)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-09 22:12:54.670 11723-11723/de.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-09 22:12:54.671 11723-11723/de.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mikepenz** [comment]
@DrFornax hmmm it does not have a reference to the library. I really have no clue what might cause it. 

For your case. You want to have an icon always on the beginning of the text? 

I suggest to use a `Compound` drawable. it is the proper way for doing something like this. 

The `PlaygroundActivity` showcases this

**Comment by mikepenz** [comment]
@DrFornax can you provide a sample implementation which showcases this crash? 

did you try the proper implementation using a compound drawable?

**Comment by DrFornax** [comment]
The icon is not always at the beginning of the text. A server sends messages and puts the icons in the flowing text.

I really try to find out where the problem is. Unfortunately I am not allowed to paste some code, yet but will try to find out if I could isolate the problem or send you some code to reproduce the problem.

Since this is a part time project and I'm not working on it all the time, it unfortunately always takes a bit to answer. I'm sorry for this.

**Comment by mikepenz** [comment]
@DrFornax thank you for the answer. 

I can only assume that you do not set it in the main thread? 

You might also want to try and not use the `IconicsContextWrapper` but instead a normal `IconicsTextView` and just apply the text via this approach. 

I hope something of these things solve sit for you

**Comment by hurshi** [comment]
Hi,I have a same exception
and I can provide source code:(I create a demo at Android-Iconics project
### source code
there are only two file 
```
package com.mikepenz.iconics.sample;

import android.os.Bundle;
import android.support.v4.view.LayoutInflaterCompat;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.mikepenz.google_material_typeface_library.GoogleMaterial;
import com.mikepenz.iconics.context.IconicsLayoutInflater2;

public class ExceptionActivity extends AppCompatActivity {

    private TextView normalTv;
    private LinearLayout ll;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        LayoutInflaterCompat.setFactory2(getLayoutInflater(), new IconicsLayoutInflater2(getDelegate()));
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_exception);

        ll = (LinearLayout) findViewById(R.id.clickme);
        normalTv = (TextView) findViewById(R.id.normal_textview);

        normalTest();
        errorTest();
    }


    private void normalTest() {
        L(normalTv.getText().toString());
        normalTv.setText(GoogleMaterial.Icon.gmd_access_time.getFormattedName());
        L(normalTv.getText().toString());
        normalTv.setText(GoogleMaterial.Icon.gmd_3d_rotation.getFormattedName());
    }

    int index = 0;

    private void errorTest() {
        ll.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                switch (index) {
                    case 0:
                        normalTv.setText(GoogleMaterial.Icon.gmd_access_time.getFormattedName());
                        break;
                    case 1:
                        normalTv.setText(GoogleMaterial.Icon.gmd_3d_rotation.getFormattedName());
                        break;
                    case 2:
                        normalTv.setText(GoogleMaterial.Icon.gmd_ac_unit.getFormattedName());
                        break;
                    case 3:
                        normalTv.setText(GoogleMaterial.Icon.gmd_zoom_out_map.getFormattedName());
                        break;
                }
                index++;
            }
        });
    }

    private void L(String str) {
        Log.e(">>>", str);
    }
}

```
the layout:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:id="@+id/clickme"
        android:layout_width="200dp"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/normal_textview"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:textSize="30dp" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Click Me"
            android:textSize="30dp" />
    </LinearLayout>
</RelativeLayout>

```

and change AndroidManifest.xml like
```
 <activity android:name=".ExceptionActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```
there will be a IndexOutOfBoundsException after you click 

### temporary Solution
do not set layout_width="0dp" can temporary solve this exception,but this is not Completely,I have this exception again with one time(not always appear)
there are source code:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:id="@+id/clickme"
        android:layout_width="200dp"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/normal_textview"
            android:layout_width="1dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:textSize="30dp" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Click Me"
            android:textSize="30dp" />
    </LinearLayout>
</RelativeLayout>

```
### else
if you can not appear again,please let me know,I can provide a independent project for you,Thanks

**Comment by hurshi** [comment]
@mikepenz ???

**Comment by mikepenz** [comment]
@hurshi I'll have a look. It takes a bit. I am super flooded with work and life, ..

**Comment by mikepenz** [comment]
Ok so after looking into it. 

The issue is caused by the following:
WIth the `IconicsLayoutInflater2` I'll automatically replace text with the icon + attach a text listener to the textview. 

When we then adjust the text the normal `draw` logic instantly kicks in of the textview, during this time we get the event of the `TextWatcher` with the editable, which we modify to be the icon. 
The problem here is though, that the `draw` logic of the `TextView` is too stupid and does not detect that instead of multiple lines (the text for the icon would result in 4 lines) is now only 1 line (the icon is super short, the text behind is also super short, so no line break necessary) So it will blow up. There's sadly not much we can do about this (setting the lines, and line number to 1 surprisingly does not change the internal line calculation :D)

The easiest approach to get around this is use the `IconicsTextView` as this will adjust the icon during `setText`, another approach (but not so handy) would be to apply the styling to the text as spannable, and apply this then to the normal `TextView` (so it would have the short string from the beginning) 

Another nice workaround is to add `android:ellipsize="start"` to that `TextView` as this will change the way it calculates line breaks, and it won't crash anymore.
