### ISSUE TITLE
Crash on updating to 3.0.0

### ISSUE THREAD

**Issue by vivekav-96** [mikepenz/Android-Iconics#358]
IconicsImagView was working fine until 2.9.3
Then I Updated to 2.9.5, was causing to crash the application.  (Nothing changed in Java or XML code)
Then I rolled back to 2.9.3 and everything worked fine.
Now on 3.0.0 release, tried upgrading was causing crashes. (Nothing changed in Java or XML code)
Tried cleaning and building project. No use.

Posting the entire crash log on updating to 3.0.0

[crash log.txt](https://github.com/mikepenz/Android-Iconics/files/1517996/crash.log.txt)

> FATAL EXCEPTION: main
                                                                          Process: com.teknowmics.smartdocs, PID: 16879
                                                                          android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.mikepenz.iconics.view.IconicsImageView
                                                                          Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.mikepenz.iconics.view.IconicsImageView
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                              at com.teknowmics.smartdocs.view.adapters.FileFolderListAdapter.onCreateViewHolder(FileFolderListAdapter.java:70)
                                                                              at com.teknowmics.smartdocs.view.adapters.FileFolderListAdapter.onCreateViewHolder(FileFolderListAdapter.java:36)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                                              at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                              at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                              at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
12-01 23:03:54.287 16879-16879/com.teknowmics.smartdocs E/AndroidRuntime:     at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at com.android.internal.policy.DecorView.onLayout(DecorView.java:934)
                                                                              at android.view.View.layout(View.java:18878)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2684)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                           Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/iconics/internal/IconicsViewsAttrsApplier;
                                                                              at com.mikepenz.iconics.view.IconicsImageView.applyAttr(IconicsImageView.java:60)
                                                                              at com.mikepenz.iconics.view.IconicsImageView.initialize(IconicsImageView.java:54)
                                                                              at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:44)
                                                                              at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:38)
                                                                              	... 85 more
                                                                           Caused by: java.lang.ClassNotFoundException: com.mikepenz.iconics.internal.IconicsViewsAttrsApplier
                                                                              at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                              at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                              	... 89 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/iconics/context/IconicsAttrsApplier;
                                                                              	... 89 more
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.context.IconicsAttrsApplier" on path: DexPathList[[zip file "/data/app/com.teknowmics.smartdocs-2/base.apk"],nativeLibraryDirectories=[/data/app/com.teknowmics.smartdocs-2/lib/arm, /data/app/com.teknowmics.smartdocs-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                              	... 89 more

**Comment by mikepenz** [comment]
@vivekav-96 did you read the upgrade notes?
https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md#295

**Comment by vivekav-96** [comment]
I've added Iconics **View** library until 2.9.3
On higher versions, I needed to add both the **View** and **Core** library.
Fixed the issue.
Thank you for the support and the awesome library @mikepenz
