### ISSUE TITLE
Can't load IconicsDrawable with Glide.

### ISSUE THREAD

**Issue by 4Face** [mikepenz/Android-Iconics#361]
## About this issue

- Briefly describe the issue:
I can't load an IconicsDrawable with Glide.
E/GlideExecutor: Request threw uncaught throwable                                                                      com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.mikepenz.iconics.IconicsDrawable@541b05d

Is there any way to fix it? I wanna use it as a "custom placeholder" with return !StringUtils.isEmptyString(pictureUrl) ? pictureUrl : errorDrawable; so I can apply Glide Transomations.

- How can the issue be reproduced / sample code:

```java
private Drawable errorDrawable = new IconicsDrawable(itemView.getContext())
                .icon(MaterialDrawerFont.Icon.mdf_person)
                .colorRes(R.color.md_grey_300)
                .backgroundColorRes(R.color.md_white_1000);

Glide.with(itemView.getContext())
                    .load(getProfilePicture(user.getPictureUrl()))
                    .apply(RequestOptions.circleCropTransform())
                    .into(pictureView);

private Object getProfilePicture(String pictureUrl) {
    return !StringUtils.isEmptyString(pictureUrl) ? pictureUrl : errorDrawable;
}
```

Full stacktrace:
E/GlideExecutor: Request threw uncaught throwable
                                                                         com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.mikepenz.iconics.IconicsDrawable@541b05d
                                                                             at com.bumptech.glide.Registry.getModelLoaders(Registry.java:543)
                                                                             at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:186)
                                                                             at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:204)
                                                                             at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:41)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:762)
                                                                             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)

## Details
- [y] Used library version
- [n] Used support library version
- [n] Used gradle build tools version
- [n] Used tooling / Android Studio version
- [n] Other used libraries, potential conflicting libraries

## Checklist

- [y] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [y] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [y] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [y] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [y] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [y] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@4Face glide is meant to load resources or images from the web. not for `Drawables`

you can set the `IconicsDrawable` as normal drawable to that view.
the issue is not related to this library. 

Just use glide correctly. Please find more details in the glide library
