### ISSUE TITLE
Crash on getDefinedFonts

### ISSUE THREAD

**Issue by Aqua-Ye** [mikepenz/Android-Iconics#374]
## About this issue

- I see crashes for people using Android 5, mostly Samsung devices, when calling `init` method.
- Here is the complete crash log:
```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=5475
       at java.lang.reflect.ArtField.getNameNative(ArtField.java)
       at java.lang.reflect.ArtField.getName(ArtField.java:91)
       at java.lang.reflect.Field.getName(Field.java:122)
       at com.mikepenz.iconics.utils.GenericsUtil.getDefinedFonts(SourceFile:55)
       at com.mikepenz.iconics.utils.GenericsUtil.getFields(SourceFile:23)
       at com.mikepenz.iconics.Iconics.init(SourceFile:54)
       ...
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4934)
       at android.app.ActivityThread.access$1600(ActivityThread.java:168)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5753)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

## Details
- [3.0.2] Used library version
- [27.0.2] Used support library version
- [27.0.3] Used gradle build tools version
- [3.0.1] Used Android Studio version

Any idea what might be causing this?

**Comment by mikepenz** [comment]
Sounds like an internal crash of the Android system. Or some modified part of that OEM. 

Basically this code just checks the included ressources and tries to detect the fonts which are available:

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/utils/GenericsUtil.java#L52

**Comment by Aqua-Ye** [comment]
Thanks. That's what I understood also. I'll add a `try catch` around the `init` for the moment. Maybe can you add some check? :)

**Comment by mikepenz** [comment]
well I assume that in such a case the auto registering of fonts won't work. 

So adding a try catch won't solve it for you. There is a new release needed allowing you to manually register your font you want to use, and after that mark the `init` as done. so that it won't try this code block over and over again. otherwise you will end up in an endless loop

**Comment by mikepenz** [comment]
So in v3.0.3 I added a new method for you :)

First register the font you want, via the `registerFont` method. 

And then `markInitDone`. So it won't hit the reflection based auto detection anymore:
https://github.com/mikepenz/Android-Iconics/blob/94c247dedf8f15649ab6986a023444c95655dd00/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L27

https://github.com/mikepenz/Android-Iconics/blob/94c247dedf8f15649ab6986a023444c95655dd00/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L91

**Comment by mikepenz** [comment]
Just pushed to maven central. might take ~15-30 minutes for it to be available

**Comment by Aqua-Ye** [comment]
You are the best!! So if I understood clearly:
```
        Iconics.init(getApplicationContext());
        Iconics.registerFont(new MyIcons());
        Iconics. markInitDone();
```
Is that right?

**Comment by mikepenz** [comment]
@Aqua-Ye no `init()` required at all

**Comment by Aqua-Ye** [comment]
Gotcha! Thanks

**Comment by mikepenz** [comment]
So basically `init()` usually does the reflection based check to retrieve the fonts based on their string contained (was the best way to make it detect a module) 
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L52

So the `RegisterFont` basically does it manually, and the `markInitDone()` finishes the init step :) 

Thanks again. And sorry for the issue
