### ISSUE TITLE
Didn't find class "com.mikepenz.iconics.view.IconicsTextView" on path: DexPathList[[zip

### ISSUE THREAD

**Issue by sondangpangaribuan** [mikepenz/Android-Iconics#402]
I get this error 
 compileSdkVersion 27 
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.belisip.admin"
        minSdkVersion 18
        targetSdkVersion 27
        multiDexEnabled true
    }

implementation 'com.mikepenz:iconics-core:3.0.4'

I get this error when minSdkversion update from 16 to 18. How to solve this ??

Binary XML file line #23: Binary XML file line #23: Error inflating class com.mikepenz.iconics.view.IconicsTextView
    Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class com.mikepenz.iconics.view.IconicsTextView
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.view.IconicsTextView" on path: DexPathList[[zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/base.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_resources_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.belisip.admin.adapter.StockListAdapter.getView(StockListAdapter.java:66)
        at android.widget.AbsListView.obtainView(AbsListView.java:3189)
        at android.widget.ListView.makeAndAddView(ListView.java:2197)
        at android.widget.ListView.fillDown(ListView.java:824)
        at android.widget.ListView.fillFromTop(ListView.java:885)
        at android.widget.ListView.layoutChildren(ListView.java:1952)
        at android.widget.AbsListView.onLayout(AbsListView.java:2961)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1910)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-01 17:58:27.028 17146-17146/com.belisip.admin E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
        at android.view.View.layout(View.java:20854)
        at android.view.ViewGroup.layout(ViewGroup.java:6401)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2919)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2606)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7780)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.belisip.admin-q2VKovx5jj3-0SRxptqziQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5943)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)

**Comment by mikepenz** [comment]
you don't include the 'view' dependency: https://github.com/mikepenz/Android-Iconics#1b-optional-add-the-views-dependency

**Comment by sondangpangaribuan** [comment]
Awesomeee....

Thank you....
