### ISSUE TITLE
Problem with some Iconics dependencies in Material Drawer. How to fix?

### ISSUE THREAD

**Issue by itzThiefz-exe** [mikepenz/Android-Iconics#435]
When I use the library icons: implementation 'com.mikepenz: ionicons-typeface: 2.0.1.5', implementation 'com.mikepenz:octicons-typeface:3.2.0.5', implementation 'com.mikepenz:pixeden-7-stroke-typeface:1.2.0.3', implementation 'com.mikepenz:ionicons-typeface:2.0.1.5'. I get the following error when trying to start the activity.

`2019-02-20 19:06:57.532 484-484/network.wolfnginx.okami E/AndroidRuntime: FATAL EXCEPTION: main
    Process: network.wolfnginx.okami, PID: 484
    java.lang.AbstractMethodError: abstract method "android.graphics.Typeface com.mikepenz.iconics.typeface.ITypeface.getRawTypeface()"
        at com.mikepenz.iconics.IconicsDrawable.icon(IconicsDrawable.kt:343)
        at com.mikepenz.iconics.IconicsDrawable.<init>(IconicsDrawable.kt:110)
        at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.kt:83)
        at com.mikepenz.materialdrawer.holder.ImageHolder$Companion.decideIcon(ImageHolder.kt:116)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.kt:84)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:51)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:15)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:24)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:453)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6932)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5852)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6119)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3990)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3707)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
        at android.view.View.layout(View.java:19685)
2019-02-20 19:06:57.532 484-484/network.wolfnginx.okami E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2549)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2265)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1439)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6899)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

**Comment by mikepenz** [comment]
@itzThiefz-exe which version of iconics do you use, which version of materialDrawer do you use?

**Comment by itzThiefz-exe** [comment]
I'm using **Material Drawer 7.0.0-alpha4i** and **I'm using Iconics 3.2.1**

**Comment by mikepenz** [comment]
materialdrawer 7 uses the new iconics v4 which only has a few icon packs released at the moment. 

https://github.com/mikepenz/Android-Iconics/pull/431/files

**Comment by itzThiefz-exe** [comment]
Thanks:smile:
