### ISSUE TITLE
exception with SimpleSearchView on API16 (and probabily any  < 20)

### ISSUE THREAD

**Issue by marbat87** [mikepenz/Android-Iconics#447]
## About this issue

I'm using the SimpleSearchView custom library to integrate an animated search bar.

It is inflated in layout as follows:
```
<com.ferfalk.simplesearchview.SimpleSearchView
            android:id="@+id/searchView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/colorPrimary" />
```

With latest stable version of Android-Iconics it works on all API level.
With 4.0.0-b1 version, the error below happens on activity start for API < 20.
It seems to be an issue with IconicsAnimationProcessor.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{it.cammino.risuscito/it.cammino.risuscito.MainActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class com.ferfalk.simplesearchview.SimpleSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
        at android.app.ActivityThread.access$600(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class com.ferfalk.simplesearchview.SimpleSearchView
        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at it.cammino.risuscito.MainActivity.onCreate(MainActivity.kt:117)
        at android.app.Activity.performCreate(Activity.java:5008)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
        at android.app.ActivityThread.access$600(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at android.view.LayoutInflater.createView(LayoutInflater.java:587)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at it.cammino.risuscito.MainActivity.onCreate(MainActivity.kt:117) 
        at android.app.Activity.performCreate(Activity.java:5008) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
        at android.app.ActivityThread.access$600(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: com.mikepenz.iconics.animation.IconicsAnimationProcessor$proxyPauseListener$1
        at com.mikepenz.iconics.animation.IconicsAnimationProcessor.<init>(IconicsAnimationProcessor.kt:127)
        at com.mikepenz.iconics.animation.BlinkAlphaProcessor.<init>(BlinkAlphaProcessor.kt:41)
        at com.mikepenz.iconics.animation.BlinkAlphaProcessor.<init>(BlinkAlphaProcessor.kt:40)
        at com.mikepenz.iconics.animation.BlinkAlphaProcessor.<init>(BlinkAlphaProcessor.kt)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at com.mikepenz.iconics.Iconics.init(Iconics.kt:335)
        at com.mikepenz.iconics.Iconics.init(Iconics.kt:76)
        at com.mikepenz.iconics.Iconics.style(Iconics.kt:194)
        at com.mikepenz.iconics.Iconics$BuilderView.build(Iconics.kt:261)
        at it.cammino.risuscito.ui.IconicsFactory.onViewCreatedInternal(IconicsFactory.kt:44)
        at it.cammino.risuscito.ui.IconicsFactory.onViewCreated(IconicsFactory.kt:23)
        at it.cammino.risuscito.ui.IconicsLayoutInflater.onCreateView(IconicsLayoutInflater.kt:21)
        at androidx.core.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
    	at com.ferfalk.simplesearchview.SimpleSearchView.inflate(SimpleSearchView.java:11
```

## Details
- [ 4.0.0-b1] Used library version
- [androidx 1.0.0 ] Used support library version
- [5.3 ] Used gradle build tools version
- [ 3.3.2 ] Used tooling / Android Studio version
- [ https://github.com/Ferfalk/SimpleSearchView ] Other used libraries, potential conflicting libraries

Thanks in advance

**Comment by mikepenz** [comment]
@marbat87 the problem was fixed in the v3.x release. 

v4.x was not yet updated as we do some work on it. there will be an update to the beta soon again.

**Comment by marbat87** [comment]
@mikepenz Thank you very much.

**Comment by mikepenz** [comment]
v4.0.0-rc01 released which should contain the fix
