### ISSUE TITLE
com.mikepenz.iconics.view.IconicsImageView 

### ISSUE THREAD

**Issue by bmutinda** [mikepenz/Android-Iconics#45]
com.mikepenz.iconics.view.IconicsImageView has never worked in my project. What actually do I do wrong? 

This is what I have in my xml
```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
	....>
	
	<com.mikepenz.iconics.view.IconicsImageView
		android:id="@+id/favorite_channel_icon"
		android:layout_width="50dp"
		android:layout_height="50dp"
		android:padding="5dp"
		app:iiv_icon="faw-android"/>
		
</LinearLayout>

**Comment by mikepenz** [comment]
seems correct if you look at the sample app:

```
<com.mikepenz.iconics.view.IconicsImageView
                    android:layout_width="72dp"
                    android:layout_height="72dp"
                    app:iiv_color="@android:color/holo_red_dark"
                    app:iiv_icon="gmd-favorite" />
```

**Comment by bmutinda** [comment]
I also wonder why its not working. Every time I add that to any layout, the app crashes but setting the drawable with java works fine.

**Comment by mikepenz** [comment]
@bmutinda the app crashes. what'S the output?

**Comment by bmutinda** [comment]
I will paste the output once I get back to Android studio...

**Comment by mikepenz** [comment]
@bmutinda ok good

**Comment by bmutinda** [comment]
Here is the error log
```java 

android.view.InflateException: Binary XML file line #21: Error inflating class com.mikepenz.iconics.view.IconicsImageView
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
....................
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.view.IconicsImageView" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/ke.co.zuku.zukuapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/ke.co.zuku.zukuapp-2, /vendor/lib, /system/lib, /data/datalib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)

```
Just wondering why this ClassNotFound exception and the library is loaded correctly in my graddle script.
compile 'com.mikepenz.iconics:library:0.7.9@aar'

**Comment by mikepenz** [comment]
@bmutinda i think you should update to v1.2.0 the `com.mikepenz.iconics.view.IconicsImageView` was renamed in a newer version. v0.7.9 still has a different path for the view
