### ISSUE TITLE
IconicsLayoutInflater causes Stackoverflow

### ISSUE THREAD

**Issue by Nailik** [mikepenz/Android-Iconics#453]
I have an Android 4.4.3 Devices that crashes when i `setText` or  `setMovementMethod `and use `LayoutInflaterCompat.setFactory2(getLayoutInflater(), new IconicsLayoutInflater2(getDelegate()));` (no difference if i use the old Factory), also the `IconicsContextWrapper.wrap(newBase)` causes this issue.
It's a "Zebra Technologies TC75" known as "Symbol"

```
W/ResourceType: Attempt to retrieve bag 0x7f120016 which is invalid or in a cycle.

[ repeats lots of times ]

android.view.InflateException: Binary XML file line #21: Error inflating class <unknown>
     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
     at android.widget.Toast.makeText(Toast.java:245)
     at android.widget.Editor.<init>(Editor.java:222)
     at android.widget.TextView.createEditorIfNeeded(TextView.java:8782)
     at android.widget.TextView.setText(TextView.java:3728)
     at android.widget.TextView.setText(TextView.java:3671)
     at android.widget.TextView.setText(TextView.java:3646)
 
	[ repeats lots of times ]

     at android.widget.Toast.makeText(Toast.java:247)
     at android.widget.Editor.<init>(Editor.java:222)
     at android.widget.TextView.createEditorIfNeeded(TextView.java:8782)
     at android.widget.TextView.setText(TextView.java:3728)
     at android.widget.TextView.setText(TextView.java:3671)
     at android.widget.TextView.setText(TextView.java:3646)
     at android.widget.TextView.setMovementMethod(TextView.java:1660)
   
	[ a "setText" call]

     at androidx.fragment.app.Fragment.performResume(Fragment.java:2498)
     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
     at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
     at android.os.Handler.handleCallback(Handler.java:733)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5034)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
     at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Constructor.constructNative(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
 	... 424 more
 Caused by: java.lang.StackOverflowError
     at android.util.SparseArray.get(SparseArray.java:102)
     at android.content.res.StringBlock.get(StringBlock.java:70)
     at android.content.res.AssetManager.getPooledString(AssetManager.java:275)
     at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:727)
     at android.content.res.TypedArray.getValueAt(TypedArray.java:712)
     at android.content.res.TypedArray.getDrawable(TypedArray.java:592)
     at android.view.View.<init>(View.java:3554)
     at android.view.ViewGroup.<init>(ViewGroup.java:470)
     at android.widget.LinearLayout.<init>(LinearLayout.java:176)
     at android.widget.LinearLayout.<init>(LinearLayout.java:172)

 	... 427 more

```
I hope you can help me in any way.

Edit:
The "Android-Iconics" App from PlayStore also crashes, when i fork this Project and debug the App on the devices it starts - very curious.

Edit2: 
After adding the Inflator the forked Project crashes too.

Edit3:
When i manually use `new Iconics.IconicsBuilder().ctx(getContext()).on(textView).build()` it works, but in my opinion it's not a nice solution.

**Comment by mikepenz** [comment]
@Nailik thank you very much for the report. 

Sadly we do not have this device available so it is gonna be impossible for us to debug. 
There is a chance that this devices OS has a platform issue not playing nicely with the inflater.

Do you have any stacktrace or any output referencing back to the Android-Iconics code which might causes this stackovereflow?

**Comment by Nailik** [comment]
So debugging is not easy because it seems to be sth in the Android System. I duplicated and overwritten the `IconicsFactory` and commented out the `addTextChangedListener` for the `TextViews`.
The problem seems NOT to be the combination of `Iconics.IconicsBuilder()` and the `addTextChangedListener` in the `onViewCreatedInternal` Method. Because only removing the changed Listener stops from crashing.

**Comment by Nailik** [comment]
I'm pretty sure it's a device related Problem.
I "fixed" it by only using the iconics views where i set the icons.
For a `html link` textview i used a normal textview and added the `IconicsDrawable ` as `CompoundDrawable` because `IconicsTextView` doesn't support links in html text. (Just in case anyone has the same problem)
