### ISSUE TITLE
withIcon+MaterialDrawer crashed app

### ISSUE THREAD

**Issue by armavion** [mikepenz/Android-Iconics#458]
Hello

These are the dependencies:

``` 
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.mikepenz:iconics-core:4.0.0"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'

    implementation 'com.google.android.material:material:1.1.0-alpha07'

    implementation "androidx.recyclerview:recyclerview:1.1.0-alpha06"
    implementation "androidx.annotation:annotation:1.1.0"

    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation 'com.mikepenz:google-material-typeface:3.0.1.4.original-kotlin@aar'
    implementation "com.mikepenz:materialdrawer:6.1.1"
}
```

Now here's the drawer code itself:

```
val item1 = PrimaryDrawerItem().withIdentifier(1).withName("folan")
        val item2 = SecondaryDrawerItem().withIdentifier(2).withName("folan2")

        findViewById<Button>(R.id.button55).setOnClickListener {
            Toast.makeText(applicationContext, "salam", Toast.LENGTH_SHORT).show();
        };


        val result = DrawerBuilder()
            .withActivity(this)
            .addDrawerItems(
                item1.withTextColor(Color.RED).withIcon(GoogleMaterial.Icon.gmd_accessibility),
                DividerDrawerItem(),
                item2,
                SecondaryDrawerItem().withName("folan3")
            )
            .withOnDrawerItemClickListener(object : Drawer.OnDrawerItemClickListener {
                override fun onItemClick(view: View, position: Int, drawerItem: IDrawerItem<*, *>): Boolean {

                    return true;
                }
            }).withDrawerGravity(Gravity.END)
            .build()
```

I have used withIcon() using a google material icon.

The app crashes at launch and says:

java.lang.NoSuchMethodError: No virtual method color(I)Lcom/mikepenz/iconics/IconicsDrawable; in class Lcom/mikepenz/iconics/IconicsDrawable; or its super classes (declaration of 'com.mikepenz.iconics.IconicsDrawable' appears in /data/app/com.armankarimi.omgapp-pJVuOe4S8L2jEKe5iYtSsw==/split_lib_dependencies_apk.apk)
    at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:101)
        at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:135)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:98)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
...

Would you please help me solve it? 
Thanks

**Comment by mikepenz** [comment]
@armavion you need to update your MaterialDrawer to v7.0.0-rc01 if you want to use the latest `Android-Iconics` as v6 only includes the old v3 iconics (and the interface changed a bit for it)

**Comment by armavion** [comment]
Thanks Mike 👍
