### ISSUE TITLE
AbstractMethodError: ITypeface.getRawTypeface()

### ISSUE THREAD

**Issue by m-rm** [mikepenz/Android-Iconics#463]
## About this issue

I just tried to migrate from 3.x to 4.x but I'm getting the following error message:
```
2019-06-28 10:52:28.021 5284-5284/my.package.name E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.package.name, PID: 5284
    java.lang.AbstractMethodError: abstract method "android.graphics.Typeface com.mikepenz.iconics.typeface.ITypeface.getRawTypeface()"
        at com.mikepenz.iconics.IconicsDrawable.icon(IconicsDrawable.kt:355)
        at my.package.name.login.LoginUsernameFragment.onActivityCreated(LoginUsernameFragment.kt:38)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
        at android.app.Activity.performStart(Activity.java:6992)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

I'm using this code, which should be fine according to the README:
```
        val cancelIcon = IconicsDrawable(activity).icon(CommunityMaterial.Icon.cmd_close).colorRes(R.color.fab_icon_color).sizeRes(R.dimen.fab_icon_size)
        val nextIcon = IconicsDrawable(activity).icon(CommunityMaterial.Icon.cmd_arrow_right).colorRes(R.color.fab_icon_color).sizeRes(R.dimen.fab_icon_size)

        login_button_start.setImageDrawable(cancelIcon)
        login_button_end.setImageDrawable(nextIcon)
```

## Details

```
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.40"
    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation "com.mikepenz:iconics-core:4.0.0"
    implementation 'com.mikepenz:community-material-typeface:3.5.95.1@aar'
```

  - Used gradle build tools version: 3.4.1
  - Used tooling / Android Studio version: 3.4.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by zTrap** [comment]
You need to use Kotlin version of typeface library too
`implementation 'com.mikepenz:community-material-typeface:3.5.95.1-kotlin@aar'`

**Comment by m-rm** [comment]
You are right. Thank you! I checked if versions match, but didn't see the "-kotlin" postfix.

**Comment by RahulSDeshpande** [comment]
I am facing the same issue, I tried adding all the possible dependencies to the project, but nothing works.
Now it has all has become so confusing!! :(

Even if I add all the latest dependencies, it still crashes with the same error log:
```
java.lang.AbstractMethodError: abstract method "android.graphics.Typeface com.mikepenz.iconics.typeface.ITypeface.getRawTypeface()"
        at com.mikepenz.iconics.IconicsDrawable.icon(IconicsDrawable.kt:355)
```

**Comment by zTrap** [comment]
@RahulSDeshpande  Can you run `./gradlew build --scan`, publish result and post here link?

**Comment by RahulSDeshpande** [comment]
@zTrap & @mikepenz

I am now able to make it work :)
My project's dependency list is now concise & looks like:
```
implementation 'com.mikepenz:iconics-core:5.0.2@aar'
implementation 'com.mikepenz:iconics-views:5.0.2@aar'
implementation 'com.mikepenz:ionicons-typeface:2.0.1.4@aar'
implementation 'com.mikepenz:ionicons-typeface:2.0.1.5-kotlin@aar'
```

Thanks guys!

**Comment by zTrap** [comment]
@RahulSDeshpande 

`implementation 'com.mikepenz:ionicons-typeface:2.0.1.4@aar'` This row is redundant. Gradle will use only: `implementation 'com.mikepenz:ionicons-typeface:2.0.1.5-kotlin@aar'`

**Comment by RahulSDeshpande** [comment]
Got it, thanks a lot :)

Cheers 👍
