### ISSUE TITLE
NPE while inflating menu items

### ISSUE THREAD

**Issue by codedsun** [mikepenz/Android-Iconics#480]
## About this issue

- I am using menu items and toolbar which have icons set from IconicsDrawable

Log:

```
 android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.appcompat.view.menu.MenuItemImpl.showsTextAsAction()' on a null object reference
        at androidx.appcompat.view.menu.ActionMenuItemView.updateTextButtonVisibility(ActionMenuItemView.java:190)
        at androidx.appcompat.view.menu.ActionMenuItemView.setIcon(ActionMenuItemView.java:233)
        at com.mikepenz.iconics.context.IconicsFactory.onViewCreatedInternal(IconicsFactory.kt:55)
        at com.mikepenz.iconics.context.IconicsFactory.onViewCreated(IconicsFactory.kt:39)
        at com.mikepenz.iconics.context.InternalLayoutInflater$PrivateWrapperFactory2.onCreateView(InternalLayoutInflater.kt:233)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.kt:80)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidx.appcompat.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:167)
        at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:186)
        at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
        at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:473)
        at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1182)
        at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
        at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
        at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1096)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:461)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

## Details

- [x] Used library version- v4.0.2
- [x] Used support library version - 1.1.0
- [x] Used gradle build tools version - 29.0.2
- [x] Used tooling / Android Studio version - Android Studio 3.5.1
- [x] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Android 10 changed something regarding the inflater which is no longer compatible. for that matter the layout inflater and context wrapper have been deprecated and removed in the latest version of the library. 

Please see the following issue:
https://github.com/mikepenz/Android-Iconics/issues/470

I recommend that you no longer use the inflater or the contextWrapper and use the special Iconics* views or the drawable directly instead.

**Comment by codedsun** [comment]
@mikepenz I am setting the icons on the toolbar menu items, I have not used the Inflater of IconicsMenu but the `menuInfalter` of android system

**Comment by mikepenz** [comment]
I see the `LayoutInflator` in the stack. So you set it somewhere

```
at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.kt:80)
```
