### ISSUE TITLE
NPE on android 9 after switching from 4.0.1-b01 to 4.0.2

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#486]
My issue seems like this issue: https://github.com/mikepenz/Android-Iconics/issues/480 but if I understand you correctly, this issue should only occur on android 10, am I right? If I do understand you correctly, the cause of the issue seems not be android 10.

**My setup:**
Target SDK: _28_
Device: _Android 9_ on a Samsung S9
Iconics Version: _4.0.2_
Integration of iconics via `IconicsContextWrapper`

**Stacktrace**

	android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
		Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
		Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.appcompat.view.menu.MenuItemImpl.showsTextAsAction()' on a null object reference
			at androidx.appcompat.view.menu.ActionMenuItemView.updateTextButtonVisibility(ActionMenuItemView.java:190)
			at androidx.appcompat.view.menu.ActionMenuItemView.setIcon(ActionMenuItemView.java:233)
			at com.mikepenz.iconics.context.IconicsFactory.onViewCreatedInternal(IconicsFactory.kt:55)
			at com.mikepenz.iconics.context.IconicsFactory.onViewCreated(IconicsFactory.kt:39)
			at com.mikepenz.iconics.context.InternalLayoutInflater$PrivateWrapperFactory2.onCreateView(InternalLayoutInflater.kt:233)
			at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
			at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
			at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
			at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
			at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.kt:80)
			at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
			at androidx.appcompat.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:167)
			at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:186)
			at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
			at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:473)
			at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1182)
			at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
			at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
			at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
			at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
			at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1096)
			at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:461)
			at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
			at android.os.Handler.handleCallback(Handler.java:873)
			at android.os.Handler.dispatchMessage(Handler.java:99)
			at android.os.Looper.loop(Looper.java:214)
			at android.app.ActivityThread.main(ActivityThread.java:6986)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by mikepenz** [comment]
@MFlisar the issues have only been reported due to Android 10. 

For that matter we deprecated these and removed it from the README as it seems  to cause unreliable behavior in some cases. 

The interesting part here is that the IconicsFactory nor the IconicsContextWrapper or those related clases have not been changed in a long time :/ So I wouldn't know why this issue is occuring when you update to 4.0.2 from 4.0.1-b01. 
I would suppose that it existed before. 

Have you had any chance to debug into it and see what particular is forwarded as null?

**Comment by MFlisar** [comment]
I can repeatedly recreate this issue (it happens on app start, so it's easy to recreate) and it's happening on my android 9 device...  I did not have this issue with _4.0.1-b01_ for at least half a year in an app that's in daily use, it does not happen with the old version (non of my app's user ever had it either).

Made some tests now:

* `ActionMenuItemView.setIcon(Drawable icon)` is called
* `updateTextButtonVisibility` is called from this function
* in this function `mItemData` is `null` which causes the crash

When I check `ActionMenuItemView` is set, that there is a `void initialize(MenuItemImpl itemData, int menuType)` function in which `mItemData` is set, so I put added a breakpoint there and tried my app again. Result: `setIcon` is called without prior `initialize` call, so this seems to be the cause that `mItemData` is null

**Comment by mikepenz** [comment]
Is it already happening with 4.0.1?

**Comment by MFlisar** [comment]
This is just a quick idea, but why not call `initialise` instead of `setIcon` here? It will internally call `setIcon` as well. Probably because you can't access `MenuItemImpl`? did not check this, just wanted to throw this in...
https://github.com/mikepenz/Android-Iconics/blob/30287ed7aa625af4f8e06e4586fcb8ace303b898/library-core/src/main/java/com/mikepenz/iconics/context/IconicsFactory.kt#L55

To your question, version _4.0.1_ does still work, so the crash happens when switching from _4.0.1_  to _4.0.2_

**Comment by mikepenz** [comment]
Basically I would assume that the system default should happen here. e.g. we shouldn't call things the system should call

Very interesting. I don't see how those changes would result in this strange behavior: https://github.com/mikepenz/Android-Iconics/commit/bca2a41a7b0d7ac6cccab9e74dfa9d376b38a4fd

**Comment by MFlisar** [comment]
Not even a dependency upgrade as far as I see, it's really weird that it suddenly fails...

Regarding "system default", I don't see that calling initialise would not be the default, e.g. in the `MenuAdapter` class, google uses initialise as well:
https://android.googlesource.com/platform/frameworks/support/+/237c8946756af4b0fe9d0fa3965593e247d53698/appcompat/src/main/java/androidx/appcompat/view/menu/MenuAdapter.java#109

**Comment by mikepenz** [comment]
this is a particular adapter providing a custom menu, which we do not have in our case. 

Also I do not see where we would have a MenuItemImpl available in that case, so I suppose the only solution will be to remove support for the automatic inflation all-together

**Comment by MFlisar** [comment]
> I do not see where we would have a MenuItemImpl available in that case

I thought so, have not checked this... But for me it looks like this function is meant for the use case:

    interface ItemView {
        /**
         * Initializes with the provided MenuItemData.  This should be called after the view is
         * inflated.
         * @param itemData The item that this ItemView should display.
         * @param menuType The type of this menu, one of
         *            {@link MenuBuilder#TYPE_ICON}, {@link MenuBuilder#TYPE_EXPANDED},
         *            {@link MenuBuilder#TYPE_DIALOG}).
         */
        void initialize(MenuItemImpl itemData, int menuType);

Sadly, the `ActionMenuItemView` holds an instance of `MenuItemImpl` and not of an interface, so we can't even set it to a custom implementation either here... Don't see a solution here either sadly

**Comment by MFlisar** [comment]
So your current suggestion is:

* remove automatic inflation
* use `Iconics<...>View` instead of `<...>View` instead
* nothing to change for menus, as those must be handled via `IconicsMenuInflaterUtil´ anyways

Did I forget something that I must care of if I remove the automatic inflation?

**Comment by mikepenz** [comment]
for the issue. it puzzles me that 4.0.2 introduces it which basically does not changes to all of this it seems :/ I honestly have no clues right now what could be the culprint

@MFlisar my suggestions are:

- remove inflation / iconics context wrapper
- use either `Iconics<...>View` or the `IconicsDrawable` programmatically (we might get xml drawable support in the next version via a different approach
- for menus similar. use the `IconicsDrawable` programmatically

**Comment by EngMah96** [comment]
I'm getting the same issue too, @mikepenz  any solution for it?

**Comment by mikepenz** [comment]
@EngMah96 https://github.com/mikepenz/Android-Iconics/issues/486#issuecomment-573021155 

- remove inflation / iconics context wrapper
- use either `Iconics<...>View` or the `IconicsDrawable` programmatically (we might get xml drawable support in the next version via a different approach
- for menus similar. use the `IconicsDrawable` programmatically
