### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.typeface.IconicsInitializer"

### ISSUE THREAD

**Issue by nmaupu** [mikepenz/Android-Iconics#630]
Hi,

## About this issue

- When trying to use Iconics in my project, everything compiles but got the following exception at runtime:\
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.typeface.IconicsInitializer" on path: DexPathList[[zip file "/data/app/~~Y9mUoGVvvs8b8dXhJS8d-g==/org.maupu.android.tmh-JGOuacTk2XqRdLx2AQKJCQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Y9mUoGVvvs8b8dXhJS8d-g==/org.maupu.android.tmh-JGOuacTk2XqRdLx2AQKJCQ==/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.mikepenz.iconics.typeface.library.community.material.Initializer.dependencies(Unknown Source:0) 
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:168) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7462) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

## Details
- [ ] Used library version
v5.4.0

- [ ] Used gradle build tools version
7.3.1

- [ ] Used tooling / Android Studio version
2021.3.1 Patch 1

Related to #582  but the workaround doesn't fix the issue ( I got a class conflict in that case)

Anyone knows how to fix that ?

**Comment by mikepenz** [comment]
This class is within the: [iconics-typeface-api](https://github.com/mikepenz/Android-Iconics/tree/develop/iconics-typeface-api) module. 

Does this issue occur for debug or release mode builds?

**Comment by arash-ahmadi** [comment]
Hi, were you able to fix this issue?

**Comment by mikepenz** [comment]
@arash-ahmadi there was never an answer from the original author of this ticket, as such I lack information. 

This crash does not occur in the sample app, which means I rely on the support of the reportee
