### ISSUE TITLE
Simple way to use in API 15?

### ISSUE THREAD

**Issue by jansallads** [mikepenz/Android-Iconics#76]
Hi Mike,

is there a simple way to use this in API 15? Android Studio just popped up an error that the library uses API 16 calls and I would love to make my app API 15 compatible.

Thanks in advance! :)

**Comment by mikepenz** [comment]
@jansallads i use it with API 10. Which method is used which is not compatible?

**Comment by jansallads** [comment]
Yeah that is what I read afterwards.

I used a simple (from my mind, I'm on the train):

new ImageDrawable().withIcon(GoogleMaterial.Icons....gmd_collections);

inside a myImageView.setDrawable() to set the icon to the ImageView, when
Android Studio instantly popped up an error that this would require minSdk
to be 16.
Am 01.09.2015 08:30 schrieb "Mike Penz" <notifications@github.com>:

**Comment by mikepenz** [comment]
@jansallads i do not have any issues with the Android-Iconics in API 10 (and i use it in many apps with a lot of installs) 

If you show me the exact spot of the warning i will probably be able why it's there. But you can safely use it with API 10.

**Comment by jansallads** [comment]
Not forgotten, I'll get back to you about this, asap :)

**Comment by besharati-behzad** [comment]
it has no issue with API 10 with i inject the context but when i follow the step 3 it produce an exception :)
BTW i have a fragment in my activity. i think it's the reason of exception.

**Comment by mikepenz** [comment]
@besharati-behzad which exception? i can't really tell without any detailed report what's going on.

**Comment by besharati-behzad** [comment]
Thank u mike.
this is the full stack trace.

12-22 19:55:23.157 14174-14174/com.behzad.mars E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.behzad.mars/com.behzad.mars.activities.BaseActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class fragment
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:117)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:123)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:3683)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:507)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class fragment
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:581)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                     at com.behzad.mars.activities.BaseActivity.onCreate(BaseActivity.java:66)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663) 
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:117) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:123) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:3683) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:507) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: java.lang.ClassNotFoundException: android.view.fragment in loader dalvik.system.PathClassLoader[/data/app/com.behzad.mars-2.apk]
                                                                     at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:471)
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:549)
                                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:623) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:408) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:320) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:276) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                     at com.behzad.mars.activities.BaseActivity.onCreate(BaseActivity.java:66) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663) 
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:117) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:123) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:3683) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:507) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
12-22 19:55:53.468 14174-14174/? I/Process: Sending signal. PID: 14174 SIG: 9

**Comment by mikepenz** [comment]
@besharati-behzad your stacktrace does not contain a single line specific to the Android-Iconics. What's your layout you try to inflate? Are you sure it's a Android-Iconics issue

**Comment by besharati-behzad** [comment]
it happens just after executing following statement:

 LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
 super.onCreate(savedInstanceState);

**Comment by besharati-behzad** [comment]
and this is my layout

<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/container_toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <include
                android:id="@+id/toolbar"
                layout="@layout/toolbar" />
        </LinearLayout>

        <FrameLayout
            android:id="@+id/container_body"
            android:layout_width="fill_parent"
            android:layout_height="0dp"
            android:layout_weight="1" />


    </LinearLayout>


    <fragment
        android:id="@+id/fragment_navigation_drawer"
        android:name="com.behzad.mars.fragments.FragmentDrawer"
        android:layout_width="@dimen/nav_drawer_width"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:layout="@layout/fragment_navigation_drawer"
        tools:layout="@layout/fragment_navigation_drawer" />

</android.support.v4.widget.DrawerLayout>

**Comment by besharati-behzad** [comment]
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/container_toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <include
                android:id="@+id/toolbar"
                layout="@layout/toolbar" />
        </LinearLayout>

        <FrameLayout
            android:id="@+id/container_body"
            android:layout_width="fill_parent"
            android:layout_height="0dp"
            android:layout_weight="1" />


    </LinearLayout>


    <fragment
        android:id="@+id/fragment_navigation_drawer"
        android:name="com.behzad.mars.fragments.FragmentDrawer"
        android:layout_width="@dimen/nav_drawer_width"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:layout="@layout/fragment_navigation_drawer"
        tools:layout="@layout/fragment_navigation_drawer" />

</android.support.v4.widget.DrawerLayout>

**Comment by mikepenz** [comment]
@besharati-behzad you use the latest version of the library?

It may could be caused by the fragment. will have to debug it at home

**Comment by besharati-behzad** [comment]
actualy it happen when i try to inflate the layout of activity

following line :
setContentView(R.layout.activity_base);

**Comment by besharati-behzad** [comment]
yes. i use the latest version :)

**Comment by mikepenz** [comment]
Yes. i saw it in the stacktrace. it works without the `IconicsLayoutInflater` right? so i think it may miss the namespace to instantiate the layouts from. will check at home

**Comment by besharati-behzad** [comment]
Yeah . it has no issue with following approach

 @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }

**Comment by besharati-behzad** [comment]
thank u mike.

**Comment by mikepenz** [comment]
@besharati-behzad the `IconicsLayoutInflater` is not causing the issue. Seems like the `AppCompatDelegate` may cause some troubles. (But then it would be a support lib issue)
